name: format
description: An extension method format() for format strings like one in Python.
version: 1.1.0
homepage: https://github.com/vi-k/format

environment:
  sdk: '>=2.13.4 <3.0.0'

dependencies:
  characters: ^1.1.0
  intl: ^0.17.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.9
